---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: SOURCE
name: "REUSE Compliance Check"
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  reuse:
    name: "REUSE Compliance Check"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "REUSE Compliance Check"
        uses: fsfe/reuse-action@v2
